image: rambabusaravanan/firebase
before_script:
  - 'echo REACT_APP_GOONG_MAP_TILES_KEY=$REACT_APP_GOONG_MAP_TILES_KEY >> .env'
stages:
  - deploy

cache:                  
  paths:                
    - node_modules/     
  key: "$CI_BUILD_REPO" 

deploy-prod:
  stage: deploy
  only:
    - master
  script:    
    - npm install
    - npm run build
    - firebase use goong-v2 --token $FIREBASE_TOKEN
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID from gitlab" --token $FIREBASE_TOKEN
